# 数据库配置
database:
  driver: 'ODBC Driver 18 for SQL Server'
  server: '192.168.200.21'
  database: 'E10'
  auth_type: 'sql'  # windows 或 sql
  echo: false  # 是否打印SQL语句

# 功能开关
features:
  email_processor:
    enabled: true
    check_interval: 60  # 检查邮件间隔（秒）
    run_on_start: true   # 启动时是否立即执行
  crawler:
    enabled: true
    schedule_time: '08:00'
    run_on_start: true   # 启动时是否立即执行

# 邮件配置
email:
  imap_server: ${EMAIL_IMAP_SERVER}
  imap_port: ${EMAIL_IMAP_PORT}
  use_ssl: ${EMAIL_USE_SSL}
  username: ${EMAIL_ADDRESS}
  password: ${EMAIL_PASSWORD}
  rules_file: config/email_rules.yaml

# 爬虫配置
crawler:
  timeout: 30
  retry_times: 3
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

# ERP配置
erp:
  confidence_threshold: 0.9
  operation_delay: 1.0
  retry_interval: 5

# 文件管理
file_management:
  temp_folder: './temp'
  log_folder: './logs'
  max_temp_age: 7  # 临时文件保存天数
  gzjc_path: '\\fanlm\生产共享\工作进程 - 副本.xlsx'  # 使用双反斜杠表示网络路径
  delivery_json_save_dir: 'attachments/delivery'
  delivery_note_dir: 'attachments/delivery_notes'  # 添加送货单归档目录配置
